export { accountConfigSchema, serverConfigSchema } from "./config/model.js";
export { mailAccountsSchema, mailQuerySchema, mailPrepareSchema, mailExecuteSchema, toolSchemas } from "./mcp/schemas.js";
export { openDatabase } from "./outbox/database.js";
export { AccountRepository } from "./outbox/accounts.js";
export { OutboxRepository } from "./outbox/repository.js";
export { SafeError } from "./errors.js";
export { prepareMessage, messageIdHeader } from "./mail/prepare.js";
export { buildMime } from "./mail/mime.js";
export { KeychainCredentialStore, parseCredentialReference } from "./mail/credentials.js";
export { NodemailerSmtpAdapter, ImapFlowMailAdapter, parseSmtpEndpoint } from "./mail/adapters.js";
export type { ImapAdapter, SmtpAdapter, SmtpOutcome, NodemailerSmtpOptions, MailFolder, MailSummary, MailMessage, MailAttachment, ImapFlowClient, ImapFlowClientFactory, ImapFlowMailAdapterOptions } from "./mail/adapters.js";
export type { MailApplicationService, ApplicationCallContext, MailAccountsInput, MailQueryInput, MailPrepareInput, MailExecuteInput } from "./application/service.js";
export { MailGatewayService } from "./application/service.js";
export type { MailAdapterRegistry, SafeAccountProjection, AccountHealth } from "./application/service.js";
export { createMcpServer } from "./mcp/server.js";
export { startStdio } from "./stdio.js";
export { createRuntime, createRuntimeFromEnvironment, loadServerConfig } from "./runtime.js";
export type { MailGatewayRuntime, RuntimeDependencies } from "./runtime.js";
